#
# @file .github/workflows/integration_tests.yml
#
# Copyright (c) 2022 OPTIMETA project
# Copyright (c) 2022 Daniel Nüst
# Distributed under the GNU GPL v3. For full terms see the file LICENSE.
#
# Based on https://github.com/o2r-project/ojs-erc-plugin/blob/master/.github/workflows/cypress_test.yml
#
name: OPTIMETA Geoplugin CI Test

on:
  push:
    branches:
      - main

jobs:
  geoplugin:
    name: ${{ matrix.pkp-application }} version ${{ matrix.pkp-version }} with ${{ matrix.dbs }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        dbs: [
            #'pgsql',
            "mysql",
          ]
        pkp-application: ["ojs"]
        #'omp',
        #'ops'
        pkp-version: [
            # "3_2_1-4" or "stable-3_2_1" # > installation does not work in Cypress, but manually it does
            "3_3_0-11",
          ]
    env:
      OJS_VERSION: ${{ matrix.pkp-version }}

    steps:
      - name: Pre-pull images
        run: |
          docker pull pkpofficial/ojs:${{ matrix.pkp-version }}
          docker pull mariadb:10.2
          docker pull cypress/included:10.2.0

      - name: Install docker-compose and msgfmt
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install docker-compose
          sudo apt-get -qq install gettext

      - name: Install npm
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install composer
        uses: "ramsey/composer-install@v2"

      - name: Install plugin dependencies
        run: |
          composer update

      - name: Install test dependencies
        run: |
          npm install

      - name: Checkout theme plugin
        run: |
          cd ${{ github.workspace }}/..
          git clone https://github.com/ifgi/optimetaGeoTheme

      - name: Start OJS and database
        run: |
          docker-compose --file cypress/docker-compose-${{ matrix.dbs }}.yml up -d

      - name: Run Cypress
        run: |
          npx cypress run --headless --browser chrome

      - name: Show logs
        if: ${{ failure() }}
        run: |
          docker logs db
          docker logs ojs
          cat cypress/logs/*.log

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots for ${{ matrix.pkp-application }} with ${{ matrix.dbs }}
          path: |
            ${{ github.workspace }}/cypress/screenshots

      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: videos for ${{ matrix.pkp-application }} with ${{ matrix.dbs }}
          path: |
            ${{ github.workspace }}/cypress/videos
